export const PAGES = {
    LOGIN: 'LOGIN_PAGE',
    REGISTER: 'REGISTER_PAGE',
    ROOM: 'ROOM_PAGE',
    ROOMS: 'ROOMS_PAGE',
    INDEX: 'INDEX_PAGE'
}

export const HEADER_BUTTONS = {
    ROOMS_BTN: 'ROOMS_BUTTON',
    LOGIN_BTN: 'LOGIN_BUTTON',
    REGISTER_BTN: 'REGISTER_BUTTON',
    INDEX_PAGE_BTN: 'INDEX_PAGE_BUTTON',
    LOGOUT_BTN: 'LOGOUT_BUTTON'
}